name: Docker Image CI

on:
  push:
    branches: [ "poc" ]
  pull_request:
    branches: [ "poc" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug - list files
        run: |
          echo "PWD: $(pwd)"
          ls -la
          find . -maxdepth 3 -type f -name Dockerfile || true
          
      - name: Set BUILD_FROM
         run: echo "BUILD_FROM=debian:bullseye-slim" >> $GITHUB_ENV

      - name: Build the Docker image
         working-directory: teslamate-abrp-hassio-addon
         
  run: docker build . --tag my-image-name:$(date +%s)
      - name: Build the Docker image
        working-directory: teslamate-abrp-hassio-addon
        run: docker build . --tag my-image-name:$(date +%s)
